version: '3.9'

services:
  web:
    build: .
    command: sh gunicorn_start
    # ports: # host:container
    #   - 8000:8000
    env_file:
      - ./event/.env
    restart: always
    volumes: # host:container
      - media:/media
      - static:/static

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    depends_on:
      - web
    ports:
      - 8000:8000


volumes:
  static:
    driver: local
    driver_opts:
      type: none
      device: /event/volumes/static
      o: bind
  media:
    driver: local
    driver_opts:
      type: none
      device: /event/volumes/media
      o: bind