version: '3.9'

services:
  web:
    build: .
    command: sh gunicorn_start
    # ports: # host:container
    #   - 8000:8000
    env_file:
      - ./event/.env
    restart: unless-stopped

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - remote_static:/static
      - remote_media:/media
    depends_on:
      - web
    ports:
      - 8000:8000


volumes:
  remote_static:
    driver_opts:
      type: nfs
      o: addr=192.168.100.228,nfsvers=4
      device: :/event/static
  remote_media:
    driver_opts:
      type: nfs
      o: addr=192.168.100.228,nfsvers=4
      device: :/event/media
  remote_logs:
    driver_opts:
      type: nfs
      o: addr=192.168.100.228,nfsvers=4
      device: :/event/logs