# Generated by Django 4.1.2 on 2023-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_events/'),
        ),
    ]
