# Generated by Django 4.2 on 2023-04-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_alter_evento_cover_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Event',
        ),
    ]
