# Generated by Django 4.2 on 2023-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_rename_evento_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='time_end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
