# Generated by Django 4.2 on 2023-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_remove_event_end_at_remove_event_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
